/* Generated By:JavaCC: Do not edit this line. JarvisParserTreeConstants.java Version 5.0 */
public interface JarvisParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTECHONODE = 2;
  public int JJTANDNODE = 3;
  public int JJTORNODE = 4;
  public int JJTEQNODE = 5;
  public int JJTNENODE = 6;
  public int JJTGENODE = 7;
  public int JJTLENODE = 8;
  public int JJTGTNODE = 9;
  public int JJTLTNODE = 10;
  public int JJTPLUSNODE = 11;
  public int JJTMINUSNODE = 12;
  public int JJTMULTNODE = 13;
  public int JJTDIVNODE = 14;
  public int JJTNOTNODE = 15;
  public int JJTNEGNODE = 16;
  public int JJTINTVALNODE = 17;
  public int JJTDOUBLEVALNODE = 18;
  public int JJTBOOLVALNODE = 19;
  public int JJTSTRINGVALNODE = 20;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "EchoNode",
    "AndNode",
    "OrNode",
    "EQNode",
    "NENode",
    "GENode",
    "LENode",
    "GTNode",
    "LTNode",
    "PlusNode",
    "MinusNode",
    "MultNode",
    "DivNode",
    "NotNode",
    "NegNode",
    "IntValNode",
    "DoubleValNode",
    "BoolValNode",
    "StringValNode",
  };
}
/* JavaCC - OriginalChecksum=02288e331da7a746519acce77194e6d5 (do not edit this line) */
