/* Generated By:JJTree: Do not edit this line. JEQNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=J,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JEQNode extends SimpleNode {
  public JEQNode(int id) {
    super(id);
  }

  public JEQNode(JarvisParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70119f7a3ff56cf7ce4bcc43a82294b4 (do not edit this line) */
