/* Generated By:JJTree: Do not edit this line. JLENode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=J,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JLENode extends SimpleNode {
	public JLENode(int id) {
		super(id);
	}

	public JLENode(JarvisParser p, int id) {
		super(p, id);
	}
	public void interpret()
	{
		jjtGetChild(0).interpret();
		jjtGetChild(1).interpret();

		if (stack[top] instanceof Integer && stack[top-1] instanceof Integer)
		{
			stack[--top] = new Boolean(((Integer)stack[top]).intValue() <=
					((Integer)stack[top + 1]).intValue());
		}
		else

			stack[--top] = new Boolean(((Double)stack[top]).doubleValue() <=
					((Double)stack[top + 1]).doubleValue());
	}
}
/* JavaCC - OriginalChecksum=2ff9f9fca16ea3a0fcd687e0c1e11eb7 (do not edit this line) */
