/* Generated By:JJTree: Do not edit this line. JLTNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=J,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JLTNode extends SimpleNode {
	public JLTNode(int id) {
		super(id);
	}

	public JLTNode(JarvisParser p, int id) {
		super(p, id);
	}

	public void interpret()
	{
		jjtGetChild(0).interpret();
		jjtGetChild(1).interpret();

		if (stack[top] instanceof Integer && stack[top-1] instanceof Integer)
		{
			stack[--top] = new Boolean(((Integer)stack[top]).intValue() < 
					((Integer)stack[top + 1]).intValue());
		}
		else

			stack[--top] = new Boolean(((Double)stack[top]).doubleValue() <
					((Double)stack[top + 1]).doubleValue());
	}
}
/* JavaCC - OriginalChecksum=1fbccfff6e0774952853d73e7d94cfb1 (do not edit this line) */
