/* Generated By:JJTree: Do not edit this line. JMinusNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=J,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JMinusNode extends SimpleNode {
	public JMinusNode(int id) {
		super(id);
	}

	public JMinusNode(JarvisParser p, int id) {
		super(p, id);
	}

	public void interpret()
	{
		jjtGetChild(0).interpret();
		jjtGetChild(1).interpret();
		if (stack[top] instanceof Integer && stack[top-1] instanceof Integer)
			stack[--top] = new Integer(((Integer)stack[top]).intValue() - ((Integer)stack[top+1]).intValue());
		else
			stack[--top] = new Double(((Double)stack[top]).doubleValue() - ((Double)stack[top+1]).doubleValue());

	}
}
/* JavaCC - OriginalChecksum=876dcdd9e5610430a25f4bd0d3ad6b03 (do not edit this line) */
