/* Generated By:JJTree: Do not edit this line. JNegNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=J,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JNegNode extends SimpleNode {
  public JNegNode(int id) {
    super(id);
  }

  public JNegNode(JarvisParser p, int id) {
    super(p, id);
  }

  public void interpret()
  {
	  jjtGetChild(0).interpret();
	  if (stack[top] instanceof Integer)
		  stack[top]=new Integer(-((Integer)stack[top]).intValue());
	  else if (stack[top] instanceof Double)
		  stack[top]=new Double(-((Double)stack[top]).doubleValue());
  }

}
/* JavaCC - OriginalChecksum=5e7cc07288acb1dcb06d8d1be47a7776 (do not edit this line) */
