/* Generated By:JJTree: Do not edit this line. JNENode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=J,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JNENode extends SimpleNode {
  public JNENode(int id) {
    super(id);
  }

  public JNENode(JarvisParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02012bd60aa1e25ec15aede874165c52 (do not edit this line) */
