/* Generated By:JJTree: Do not edit this line. JOrNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=J,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JOrNode extends SimpleNode {
  public JOrNode(int id) {
    super(id);
  }

  public JOrNode(JarvisParser p, int id) {
    super(p, id);
  }

  public void interpret()
  {
	  jjtGetChild(0).interpret();
	  jjtGetChild(1).interpret();
	  stack[--top] = new Boolean(((Boolean)stack[top]).booleanValue() || ((Boolean)stack[top+1]).booleanValue());
  }

}
/* JavaCC - OriginalChecksum=6f0b0625b7153b08af1a8fd34b02826b (do not edit this line) */
