/* Generated By:JJTree: Do not edit this line. JPlusNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=J,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JPlusNode extends SimpleNode {
  public JPlusNode(int id) {
    super(id);
  }

  public JPlusNode(JarvisParser p, int id) {
    super(p, id);
  }

  public void interpret()
  {
	  jjtGetChild(0).interpret();
	  jjtGetChild(1).interpret();
	  if (stack[top] instanceof Integer && stack[top-1] instanceof Integer)
	  stack[--top] = new Integer(((Integer)stack[top]).intValue() + ((Integer)stack[top+1]).intValue());
	  else
	stack[--top] = new Double(((Double)stack[top]).doubleValue() + ((Double)stack[top+1]).doubleValue());

  }
}
/* JavaCC - OriginalChecksum=e8e31e7db2fb2f1e625530608196eafa (do not edit this line) */
