/* Generated By:JJTree: Do not edit this line. JARAndNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARAndNode extends SimpleNode {
  public JARAndNode(int id) {
    super(id);
  }

  public JARAndNode(JarvisParser p, int id) {
    super(p, id);
  }
	public void interpret()
	{
		jjtGetChild(0).interpret();
		jjtGetChild(1).interpret();
		stack[--top] = new Boolean(((Boolean)stack[top]).booleanValue() && ((Boolean)stack[top+1]).booleanValue());
	}

}
/* JavaCC - OriginalChecksum=2f0f622dbcf7903a1d4e4a2da305b1a0 (do not edit this line) */
