/* Generated By:JJTree: Do not edit this line. JARAddOper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARAddOper extends SimpleNode {
  public JARAddOper(int id) {
    super(id);
  }

  public JARAddOper(JarvisParser p, int id) {
    super(p, id);
  }
  public void interpret()
  {
	  Object o = null, p = null;
	  jjtGetChild(0).interpret();
	  o = stack[top--];
	  jjtGetChild(1).interpret();
	  p = stack[top--];
	  if (o instanceof Integer && p instanceof Integer)
	  {
		  stack[++top] = new Integer((Integer)o+(Integer)p); 
	  } else {
		  stack[++top] = new Double(
				  ((Number)o).doubleValue()+((Number)p).doubleValue()); 
	  }

  }

}
/* JavaCC - OriginalChecksum=cf51f18e184509071b289e468479874e (do not edit this line) */
