/* Generated By:JJTree: Do not edit this line. JARConcatOper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARConcatOper extends SimpleNode {
	public JARConcatOper(int id) {
		super(id);
	}

	public JARConcatOper(JarvisParser p, int id) {
		super(p, id);
	}

	public void interpret()
	{
		jjtGetChild(0).interpret();
		jjtGetChild(1).interpret();
		Object o = stack[--top], p = stack[top+1];
		stack[top] = new String( o+""+p); 
	}

}

/* JavaCC - OriginalChecksum=93493a1c6ca856454d3f36e9b20c822b (do not edit this line) */
