/* Generated By:JJTree: Do not edit this line. JARDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class JARDecl extends SimpleNode {

	public JARDecl(int id) {
		super(id);
	}

	public JARDecl(JarvisParser p, int id) {
		super(p, id);
	}
	public void interpret()
	{
				MyNode.symtab.put(((JARVarEval)jjtGetChild(0)).val, null);
	}

}
/* JavaCC - OriginalChecksum=682318417245160d8cd6fc6be0062b7c (do not edit this line) */
