/* Generated By:JJTree: Do not edit this line. JARDivOper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARDivOper extends SimpleNode {
  public JARDivOper(int id) {
    super(id);
  }

  public JARDivOper(JarvisParser p, int id) {
    super(p, id);
  }

  public void interpret()
  {
	  jjtGetChild(0).interpret();
	  jjtGetChild(1).interpret();
	  Object o = stack[--top], p = stack[top+1];
		  stack[top] = new Double(
				  ((Number)o).doubleValue()/((Number)p).doubleValue()); 

  }

}
/* JavaCC - OriginalChecksum=771b118d8d8e0e0c34fa7aab65cf6973 (do not edit this line) */
