/* Generated By:JJTree: Do not edit this line. JAREQNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JAREQNode extends SimpleNode {
  public JAREQNode(int id) {
    super(id);
  }

  public JAREQNode(JarvisParser p, int id) {
    super(p, id);
  }

public void interpret()
  {
     jjtGetChild(0).interpret();
     jjtGetChild(1).interpret();

     if (stack[top] instanceof Boolean)
        stack[--top] = new Boolean(((Boolean)stack[top]).booleanValue() ==
                                ((Boolean)stack[top + 1]).booleanValue());
     else if (stack[top] instanceof Integer)
        stack[--top] = new Boolean(((Integer)stack[top]).intValue() ==
                                ((Integer)stack[top + 1]).intValue());
	else if (stack[top] instanceof String)
        stack[--top] = new Boolean(((String)stack[top]).equals(
                                ((String)stack[top + 1])));
	else 
        stack[--top] = new Boolean(((Number)stack[top]).doubleValue() == ((Number)stack[top]).doubleValue());

  }

}
/* JavaCC - OriginalChecksum=78bc74f0999c8c69545397b583ee0843 (do not edit this line) */
