/* Generated By:JJTree: Do not edit this line. JAREcho.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JAREcho extends SimpleNode {
  public JAREcho(int id) {
    super(id);
  }

  public JAREcho(JarvisParser p, int id) {
    super(p, id);
  }
  public void interpret()
  {
	  jjtGetChild(0).interpret();
	  System.out.println(stack[top--]+ "");
  }

}
/* JavaCC - OriginalChecksum=46d88b702a811d6956cc17e7ab9c429b (do not edit this line) */
