/* Generated By:JJTree: Do not edit this line. JARElifStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARElifStatement extends SimpleNode {
  public JARElifStatement(int id) {
    super(id);
  }

  public JARElifStatement(JarvisParser p, int id) {
    super(p, id);
  }

	public void interpret()
  {
	  jjtGetChild(0).interpret();
	if (((Boolean)stack[top]).booleanValue())
	{
        jjtGetChild(1).interpret();
	}

  }
}
/* JavaCC - OriginalChecksum=d6d6a54dabe8548d26939428ef360138 (do not edit this line) */
