/* Generated By:JJTree: Do not edit this line. JARFuncexec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARFuncexec extends SimpleNode {
	String val;
  public JARFuncexec(int id) {
    super(id);
  }

  public JARFuncexec(JarvisParser p, int id) {
    super(p, id);
  }

  public void interpret() {
	  try{
		 functab.get(this.val).interpret();
	  } catch(JARError e)
	  {
	  }
  }
  @Override
  public String toString()
  {
	  return  "Funcexec " + this.val;
  }
}
/* JavaCC - OriginalChecksum=fb17d181994aaaebb9a0c5e38c77053a (do not edit this line) */
