/* Generated By:JJTree: Do not edit this line. JARFunct.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARFunct extends SimpleNode {
	String val;

  public JARFunct(int id) {
    super(id);
  }

  public JARFunct(JarvisParser p, int id) {
    super(p, id);
  }

  public void interpret()
  {
	  functab.put(this.val, (JARBlock)jjtGetChild(0));
  }
  public String toString()
  {
	  return  "Funct " + this.val;
  }


}
/* JavaCC - OriginalChecksum=a84e857b9c4060a3365b21d3344d7fd7 (do not edit this line) */
