/* Generated By:JJTree: Do not edit this line. JARGTNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARGTNode extends SimpleNode {
  public JARGTNode(int id) {
    super(id);
  }

  public JARGTNode(JarvisParser p, int id) {
    super(p, id);
  }

	public void interpret()
	{
		jjtGetChild(0).interpret();
		jjtGetChild(1).interpret();

		if (stack[top] instanceof Integer && stack[top-1] instanceof Integer)
		{
			stack[--top] = new Boolean(((Integer)stack[top]).intValue() > 
					((Integer)stack[top + 1]).intValue());
		}
		else

			stack[--top] = new Boolean(((Number)stack[top]).doubleValue() >
					((Number)stack[top + 1]).doubleValue());
	}
}
/* JavaCC - OriginalChecksum=7f810b1cd623222f1f609480bc9d2892 (do not edit this line) */
