/* Generated By:JJTree: Do not edit this line. JARInt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARInt extends SimpleNode {
	int val;

  public JARInt(int id) {
    super(id);
  }

  public JARInt(JarvisParser p, int id) {
    super(p, id);
  }
  public void interpret()
  {
	  stack[++top] = new Integer(val);
  }

  public String toString() {
	  return this.val + "";
  }

}
/* JavaCC - OriginalChecksum=17461a1d9cdabe7a326d4c1277bff278 (do not edit this line) */
