/* Generated By:JJTree: Do not edit this line. JARMinOper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARMinOper extends SimpleNode {
  public JARMinOper(int id) {
    super(id);
  }

  public JARMinOper(JarvisParser p, int id) {
    super(p, id);
  }
  public void interpret()
  {
	  jjtGetChild(0).interpret();
	  jjtGetChild(1).interpret();
	  Object o = stack[--top], p = stack[top+1];
	  if (o instanceof Integer && p instanceof Integer)
	  {
		  stack[top] = new Integer((Integer)o-(Integer)p); 
	  } else {
		  stack[top] = new Double(
				  ((Number)o).doubleValue()-((Number)p).doubleValue()); 
	  }
  }

}
/* JavaCC - OriginalChecksum=f0555df2166cb9eb066ca4e08e5effae (do not edit this line) */
