/* Generated By:JJTree: Do not edit this line. JARNENode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARNENode extends SimpleNode {
  public JARNENode(int id) {
    super(id);
  }

  public JARNENode(JarvisParser p, int id) {
    super(p, id);
  }
	public void interpret()
  {
     jjtGetChild(0).interpret();
     jjtGetChild(1).interpret();

     if (stack[top] instanceof Boolean)
        stack[--top] = new Boolean(((Boolean)stack[top]).booleanValue() !=
                                ((Boolean)stack[top + 1]).booleanValue());
     else if (stack[top] instanceof Integer)
        stack[--top] = new Boolean(((Integer)stack[top]).intValue() !=
                                ((Integer)stack[top + 1]).intValue());
	else if (stack[top] instanceof String)
        stack[--top] = new Boolean(!((String)stack[top]).equals(
                                ((String)stack[top + 1])));
	else
        stack[--top] = new Boolean(((Number)stack[top]).doubleValue() != ((Number)stack[top]).doubleValue());

  }
}
/* JavaCC - OriginalChecksum=a328f33ff1e52c6fae9cae296db2c89c (do not edit this line) */
