/* Generated By:JJTree: Do not edit this line. JAROrNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JAROrNode extends SimpleNode {
  public JAROrNode(int id) {
    super(id);
  }

  public JAROrNode(JarvisParser p, int id) {
    super(p, id);
  }
  public void interpret()
	{
		jjtGetChild(0).interpret();
		jjtGetChild(1).interpret();
		stack[--top] = new Boolean(((Boolean)stack[top]).booleanValue() || ((Boolean)stack[top+1]).booleanValue());
	}


}
/* JavaCC - OriginalChecksum=ade2278a7a1ce31fd12d483be0511d1d (do not edit this line) */
