/* Generated By:JJTree: Do not edit this line. JARString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARString extends SimpleNode {
  public JARString(int id) {
    super(id);
  }

  public JARString(JarvisParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=66b7f60f0b2d531d8d87c965bce8ba7a (do not edit this line) */
