/* Generated By:JJTree: Do not edit this line. JARVarEval.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARVarEval extends SimpleNode {
  public JARVarEval(int id) {
    super(id);
  }

  public JARVarEval(JarvisParser p, int id) {
    super(p, id);
  }
  public void interpret(){
  stack[++top] = symtab.get(((JARVarname)jjtGetChild(0)).val);
  }

}
/* JavaCC - OriginalChecksum=c22d3c7dc6a9322af7ef52b1d41bde44 (do not edit this line) */
