/* Generated By:JJTree: Do not edit this line. JARWhileStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=JAR,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class JARWhileStatement extends SimpleNode {
  public JARWhileStatement(int id) {
    super(id);
  }

  public JARWhileStatement(JarvisParser p, int id) {
    super(p, id);
  }

  public void interpret()
  {
	  while (true)
	  {
  jjtGetChild(0).interpret();
		 if (!((Boolean)stack[top]).booleanValue())
			 break;
		 else jjtGetChild(1).interpret();
	  }
  }

}
/* JavaCC - OriginalChecksum=749ea8beb2b186b7a470210cdfe0b6a3 (do not edit this line) */
